 language: scala
 scala:
   - "2.11.3"
 jdk:
   - oraclejdk8
 script:
   - sbt bp-core/compile
   - sbt bp-core/test
notifications:
  webhooks:
    urls:
      - https://empireincloud.slack.com/services/hooks/travis?token=RaRjEHR0qBr6wNvkHgqKu71f
    on_success: always
    on_failure: always
    on_start: true
