 language: scala
 scala:
   - "2.10.2"
 jdk:
   - oraclejdk7
   - openjdk7
   - openjdk6
notifications:
  webhooks:
    urls:
      - https://empireincloud.slack.com/services/hooks/travis?token=RaRjEHR0qBr6wNvkHgqKu71f
    on_success: always
    on_failure: always
    on_start: true
