 language: scala
 scala:
   - "2.11.3"
 jdk:
   - oraclejdk8
   - openjdk8
notifications:
  webhooks:
    urls:
      - https://empireincloud.slack.com/services/hooks/travis?token=RaRjEHR0qBr6wNvkHgqKu71f
    on_success: always
    on_failure: always
    on_start: true
