 language: scala
 scala:
   - "2.10.2"
 jdk:
   - oraclejdk7
   - openjdk7
   - openjdk6
notifications:
  webhooks:
    - https://empireincloud.slack.com/services/hooks/travis?token=uhRc6viHMVwXAGaUNtEQ1HoT