---
  swagger: "2.0"
  info: 
    title: "Minority Platform API"
    description: "Minority Platform"
    version: "1.0.0"
  host: api.min.ority.us
  schemes:
    - "https"
  consumes:
    - application/json
  produces: 
    - application/json